import { MigrationInterface, QueryRunner } from "typeorm";

export class WhateverName1751742380567 implements MigrationInterface {
    name = 'WhateverName1751742380567'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ussd_withdrawals\` CHANGE \`status\` \`status\` enum ('in-progress', 'pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`ussd_withdrawals\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NULL DEFAULT '() => "'mobile'"'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`status\` \`status\` enum ('in-progress', 'pending', 'successful', 'failed', 'reversed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('owner', 'employee') NULL DEFAULT '() => "'owner'"'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`type\` \`type\` enum ('personal', 'business', 'business_personal') NULL DEFAULT '() => "'personal'"'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`kyc\` \`kyc\` enum ('basic', 'intermediate', 'pro') NOT NULL DEFAULT '() => "'basic'"'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_card_details\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transaction_histories\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NOT NULL DEFAULT '() => "'mobile'"'`);
        await queryRunner.query(`ALTER TABLE \`report_preferences\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed', 'processing') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`pins\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`status\` \`status\` enum ('failed', 'sent', 'processing', 'fulfilled', 'cancelled', 'withdrawn', 'reversed') NULL DEFAULT '() => "'sent'"'`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`type\` \`type\` enum ('personal', 'business') NOT NULL DEFAULT '() => "'personal'"'`);
        await queryRunner.query(`ALTER TABLE \`otps\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`kycs\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'sent', 'successful', 'failed', 'reversed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_users\` CHANGE \`kyc\` \`kyc\` enum ('basic', 'intermediate', 'pro') NOT NULL DEFAULT '() => "'basic'"'`);
        await queryRunner.query(`ALTER TABLE \`business_users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_shareholders\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_settlement_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_transaction_histories\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NOT NULL DEFAULT '() => "'mobile'"'`);
        await queryRunner.query(`ALTER TABLE \`business_recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NULL DEFAULT '() => "'mobile'"'`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`status\` \`status\` enum ('in-progress', 'pending', 'successful', 'failed', 'reversed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_devices\` CHANGE \`created_at\` \`created_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_branches\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`blue_admins\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`beneficiaries\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`verification_platform\` \`verification_platform\` enum ('dojah', 'mono') NOT NULL DEFAULT '() => "'dojah'"'`);
        await queryRunner.query(`ALTER TABLE \`airtime_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT '() => "'pending'"'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_92558c08091598f7a4439586cd\` ON \`wallets\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c1cf06e248522005c350032ee3\` ON \`wallets\` (\`wallet_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9e144a67be49e5bba91195ef5d\` ON \`user_tokens\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_6711686e2dc4fcf9c7c83b8373\` ON \`user_accounts\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9162bf9ab4e31961a8f7932974\` ON \`transactions\` (\`transaction_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\` (\`phone\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f2c2fb415138d89ce45146e5fe\` ON \`security_questions\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b64043825b647234e0ae931644\` ON \`pins\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_e6343c7edaad580e600ba5ec75\` ON \`pilot_testers\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c74be53456bd51c31ce9f06276\` ON \`pilot_testers\` (\`phone\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a51f6f210c69af4e31800be5b1\` ON \`recovery_infos\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_bbfe1fa864841e82cff1be09e8\` ON \`kycs\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9a8a82462cab47c73d25f49261\` ON \`notifications\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_95ba1f0f7266d2c6f945adb0c1\` ON \`dashme_transactions\` (\`transaction_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b6efb89dc9d9a33223c221e98e\` ON \`business_users\` (\`phone\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_199d242ff5da3a2c4e69bd8bd4\` ON \`business_wallets\` (\`wallet_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4aca6fb35fd3ce0f57cc6cdf89\` ON \`business_settlement_accounts\` (\`business_id\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_4aca6fb35fd3ce0f57cc6cdf89\` ON \`business_settlement_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_199d242ff5da3a2c4e69bd8bd4\` ON \`business_wallets\``);
        await queryRunner.query(`DROP INDEX \`IDX_b6efb89dc9d9a33223c221e98e\` ON \`business_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_95ba1f0f7266d2c6f945adb0c1\` ON \`dashme_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a8a82462cab47c73d25f49261\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_bbfe1fa864841e82cff1be09e8\` ON \`kycs\``);
        await queryRunner.query(`DROP INDEX \`IDX_a51f6f210c69af4e31800be5b1\` ON \`recovery_infos\``);
        await queryRunner.query(`DROP INDEX \`IDX_c74be53456bd51c31ce9f06276\` ON \`pilot_testers\``);
        await queryRunner.query(`DROP INDEX \`IDX_e6343c7edaad580e600ba5ec75\` ON \`pilot_testers\``);
        await queryRunner.query(`DROP INDEX \`IDX_b64043825b647234e0ae931644\` ON \`pins\``);
        await queryRunner.query(`DROP INDEX \`IDX_f2c2fb415138d89ce45146e5fe\` ON \`security_questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_9162bf9ab4e31961a8f7932974\` ON \`transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_6711686e2dc4fcf9c7c83b8373\` ON \`user_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_9e144a67be49e5bba91195ef5d\` ON \`user_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_c1cf06e248522005c350032ee3\` ON \`wallets\``);
        await queryRunner.query(`DROP INDEX \`IDX_92558c08091598f7a4439586cd\` ON \`wallets\``);
        await queryRunner.query(`ALTER TABLE \`airtime_transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`verification_platform\` \`verification_platform\` enum ('dojah', 'mono') NOT NULL DEFAULT 'dojah'`);
        await queryRunner.query(`ALTER TABLE \`beneficiaries\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`blue_admins\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_branches\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_devices\` CHANGE \`created_at\` \`created_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`business_security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`status\` \`status\` enum ('in-progress', 'pending', 'successful', 'failed', 'reversed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NULL DEFAULT 'mobile'`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`business_recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_transaction_histories\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NOT NULL DEFAULT 'mobile'`);
        await queryRunner.query(`ALTER TABLE \`business_settlement_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_shareholders\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` CHANGE \`status\` \`status\` enum ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`business_users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_users\` CHANGE \`kyc\` \`kyc\` enum ('basic', 'intermediate', 'pro') NOT NULL DEFAULT 'basic'`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('pending', 'sent', 'successful', 'failed', 'reversed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`kycs\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`otps\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`type\` \`type\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('personal', 'business') NOT NULL DEFAULT 'personal'`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('failed', 'sent', 'processing', 'fulfilled', 'cancelled', 'withdrawn', 'reversed') NULL DEFAULT 'sent'`);
        await queryRunner.query(`ALTER TABLE \`recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`pins\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('pending', 'successful', 'failed', 'processing') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`report_preferences\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transaction_histories\` CHANGE \`client_used\` \`client_used\` enum ('desktop', 'mobile') NOT NULL DEFAULT 'mobile'`);
        await queryRunner.query(`ALTER TABLE \`user_card_details\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`kyc\` \`kyc\` enum CHARACTER SET "utf8mb3" COLLATE "utf8mb3_unicode_ci" ('basic', 'intermediate', 'pro') NOT NULL DEFAULT 'basic'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`type\` \`type\` enum CHARACTER SET "utf8mb3" COLLATE "utf8mb3_unicode_ci" ('personal', 'business', 'business_personal') NULL DEFAULT 'personal'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum CHARACTER SET "utf8mb3" COLLATE "utf8mb3_unicode_ci" ('owner', 'employee') NULL DEFAULT 'owner'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('in-progress', 'pending', 'successful', 'failed', 'reversed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`client_used\` \`client_used\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('desktop', 'mobile') NULL DEFAULT 'mobile'`);
        await queryRunner.query(`ALTER TABLE \`user_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`ussd_withdrawals\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`ussd_withdrawals\` CHANGE \`status\` \`status\` enum CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" ('in-progress', 'pending', 'successful', 'failed') NOT NULL DEFAULT 'pending'`);
    }

}
