import { MigrationInterface, QueryRunner } from "typeorm";

export class Adding2o1751805673376 implements MigrationInterface {
    name = 'Adding2o1751805673376'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`wallets\` DROP FOREIGN KEY \`wallets_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`wallet_accounts\` DROP FOREIGN KEY \`wallet_accounts_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`wallet_accounts\` DROP FOREIGN KEY \`wallet_accounts_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`user_tokens\` DROP FOREIGN KEY \`user_tokens_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`user_card_details\` DROP FOREIGN KEY \`user_card_details_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`user_accounts\` DROP FOREIGN KEY \`user_accounts_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` DROP FOREIGN KEY \`tv_transactions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`transactions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`staff_profiles\` DROP FOREIGN KEY \`staff_profiles_branch_fk\``);
        await queryRunner.query(`ALTER TABLE \`staff_profiles\` DROP FOREIGN KEY \`staff_profiles_business_id_fk\``);
        await queryRunner.query(`ALTER TABLE \`security_questions\` DROP FOREIGN KEY \`security_questions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`report_preferences\` DROP FOREIGN KEY \`FK_report_preferences_business_id\``);
        await queryRunner.query(`ALTER TABLE \`recovery_infos\` DROP FOREIGN KEY \`recovery_infos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` DROP FOREIGN KEY \`power_transactions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`pins\` DROP FOREIGN KEY \`pins_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`otps\` DROP FOREIGN KEY \`otps_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`notifications_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`kycs\` DROP FOREIGN KEY \`kycs_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`kycs\` DROP FOREIGN KEY \`kycs_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`deleted_accounts\` DROP FOREIGN KEY \`deleted_accounts_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` DROP FOREIGN KEY \`data_transactions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` DROP FOREIGN KEY \`dashme_transactions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` DROP FOREIGN KEY \`business_wallets_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` DROP FOREIGN KEY \`fk_walletsnapshot_history_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` DROP FOREIGN KEY \`business_wallet_accounts_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` DROP FOREIGN KEY \`business_wallet_accounts_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` DROP FOREIGN KEY \`fk_tv_branch_id\``);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` DROP FOREIGN KEY \`fk_tv_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` DROP FOREIGN KEY \`fk_tv_staff_id\``);
        await queryRunner.query(`ALTER TABLE \`business_settlement_accounts\` DROP FOREIGN KEY \`fk_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_shareholders\` DROP FOREIGN KEY \`business_shareholders_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_recovery_infos\` DROP FOREIGN KEY \`business_recovery_infos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_profiles\` DROP FOREIGN KEY \`fk_b_user_id\``);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` DROP FOREIGN KEY \`fk_power_branch_id\``);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` DROP FOREIGN KEY \`fk_power_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` DROP FOREIGN KEY \`fk_power_staff_id\``);
        await queryRunner.query(`ALTER TABLE \`business_pins\` DROP FOREIGN KEY \`business_pins_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` DROP FOREIGN KEY \`fk_payment_branch_id\``);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` DROP FOREIGN KEY \`fk_payment_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` DROP FOREIGN KEY \`fk_payment_staff_id\``);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` DROP FOREIGN KEY \`fk_data_branch_id\``);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` DROP FOREIGN KEY \`fk_data_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` DROP FOREIGN KEY \`fk_data_staff_id\``);
        await queryRunner.query(`ALTER TABLE \`business_branches\` DROP FOREIGN KEY \`business_branches_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` DROP FOREIGN KEY \`fk_airtime_branch_id\``);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` DROP FOREIGN KEY \`fk_airtime_business_id\``);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` DROP FOREIGN KEY \`fk_airtime_staff_id\``);
        await queryRunner.query(`ALTER TABLE \`bill_mates_favourites\` DROP FOREIGN KEY \`bill_mates_favourites_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`airtime_transactions\` DROP FOREIGN KEY \`airtime_transactions_ibfk_1\``);
        await queryRunner.query(`CREATE TABLE \`usersTest\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NULL, \`name\` varchar(255) NULL, \`nickname\` varchar(255) NULL, \`best_pal\` varchar(255) NULL, \`is_online\` varchar(255) NULL, \`is_best_friend\` tinyint NULL DEFAULT '0', \`is_new\` int NULL, \`is_old\` int NULL, \`is_brand_new\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`__drizzle_migrations\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`hash\` text NOT NULL, \`created_at\` bigint NULL, UNIQUE INDEX \`id\` (\`id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`wallets\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wallet_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wallet_snapshots\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`ussd_withdrawals\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_tokens\` CHANGE \`created_at\` \`created_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_card_details\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`report_preferences\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`pins\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`otps\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`kycs\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_settlement_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_shareholders\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` CHANGE \`created_at\` \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_devices\` CHANGE \`created_at\` \`created_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_branches\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`blue_admins\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bill_mates_favourites\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`beneficiaries\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`airtime_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_92558c08091598f7a4439586cd\` ON \`wallets\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c1cf06e248522005c350032ee3\` ON \`wallets\` (\`wallet_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\` (\`phone\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9e144a67be49e5bba91195ef5d\` ON \`user_tokens\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_6711686e2dc4fcf9c7c83b8373\` ON \`user_accounts\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9162bf9ab4e31961a8f7932974\` ON \`transactions\` (\`transaction_id\`)`);
        await queryRunner.query(`CREATE INDEX \`staff_profiles_business_id_fk\` ON \`staff_profiles\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`staff_profiles_branch_fk\` ON \`staff_profiles\` (\`branch_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f2c2fb415138d89ce45146e5fe\` ON \`security_questions\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_report_preferences_business_id\` ON \`report_preferences\` (\`business_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a51f6f210c69af4e31800be5b1\` ON \`recovery_infos\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b64043825b647234e0ae931644\` ON \`pins\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_e6343c7edaad580e600ba5ec75\` ON \`pilot_testers\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c74be53456bd51c31ce9f06276\` ON \`pilot_testers\` (\`phone\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9a8a82462cab47c73d25f49261\` ON \`notifications\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_bbfe1fa864841e82cff1be09e8\` ON \`kycs\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_95ba1f0f7266d2c6f945adb0c1\` ON \`dashme_transactions\` (\`transaction_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_199d242ff5da3a2c4e69bd8bd4\` ON \`business_wallets\` (\`wallet_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_walletsnapshot_history_business_id\` ON \`business_wallet_snapshots\` (\`business_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b6efb89dc9d9a33223c221e98e\` ON \`business_users\` (\`phone\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_tv_staff_id\` ON \`business_tv_transactions\` (\`staff_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_tv_business_id\` ON \`business_tv_transactions\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_tv_branch_id\` ON \`business_tv_transactions\` (\`branch_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4aca6fb35fd3ce0f57cc6cdf89\` ON \`business_settlement_accounts\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_b_user_id\` ON \`business_profiles\` (\`b_user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_power_staff_id\` ON \`business_power_transactions\` (\`staff_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_power_business_id\` ON \`business_power_transactions\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_power_branch_id\` ON \`business_power_transactions\` (\`branch_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_payment_staff_id\` ON \`business_payment_transactions\` (\`staff_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_payment_business_id\` ON \`business_payment_transactions\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_payment_branch_id\` ON \`business_payment_transactions\` (\`branch_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_data_staff_id\` ON \`business_data_transactions\` (\`staff_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_data_business_id\` ON \`business_data_transactions\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_data_branch_id\` ON \`business_data_transactions\` (\`branch_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_airtime_staff_id\` ON \`business_airtime_transactions\` (\`staff_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_airtime_business_id\` ON \`business_airtime_transactions\` (\`business_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_airtime_branch_id\` ON \`business_airtime_transactions\` (\`branch_id\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`fk_airtime_branch_id\` ON \`business_airtime_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_airtime_business_id\` ON \`business_airtime_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_airtime_staff_id\` ON \`business_airtime_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_data_branch_id\` ON \`business_data_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_data_business_id\` ON \`business_data_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_data_staff_id\` ON \`business_data_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_payment_branch_id\` ON \`business_payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_payment_business_id\` ON \`business_payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_payment_staff_id\` ON \`business_payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_power_branch_id\` ON \`business_power_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_power_business_id\` ON \`business_power_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_power_staff_id\` ON \`business_power_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_b_user_id\` ON \`business_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_4aca6fb35fd3ce0f57cc6cdf89\` ON \`business_settlement_accounts\``);
        await queryRunner.query(`DROP INDEX \`fk_tv_branch_id\` ON \`business_tv_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_tv_business_id\` ON \`business_tv_transactions\``);
        await queryRunner.query(`DROP INDEX \`fk_tv_staff_id\` ON \`business_tv_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_b6efb89dc9d9a33223c221e98e\` ON \`business_users\``);
        await queryRunner.query(`DROP INDEX \`fk_walletsnapshot_history_business_id\` ON \`business_wallet_snapshots\``);
        await queryRunner.query(`DROP INDEX \`IDX_199d242ff5da3a2c4e69bd8bd4\` ON \`business_wallets\``);
        await queryRunner.query(`DROP INDEX \`IDX_95ba1f0f7266d2c6f945adb0c1\` ON \`dashme_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_bbfe1fa864841e82cff1be09e8\` ON \`kycs\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a8a82462cab47c73d25f49261\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_c74be53456bd51c31ce9f06276\` ON \`pilot_testers\``);
        await queryRunner.query(`DROP INDEX \`IDX_e6343c7edaad580e600ba5ec75\` ON \`pilot_testers\``);
        await queryRunner.query(`DROP INDEX \`IDX_b64043825b647234e0ae931644\` ON \`pins\``);
        await queryRunner.query(`DROP INDEX \`IDX_a51f6f210c69af4e31800be5b1\` ON \`recovery_infos\``);
        await queryRunner.query(`DROP INDEX \`FK_report_preferences_business_id\` ON \`report_preferences\``);
        await queryRunner.query(`DROP INDEX \`IDX_f2c2fb415138d89ce45146e5fe\` ON \`security_questions\``);
        await queryRunner.query(`DROP INDEX \`staff_profiles_branch_fk\` ON \`staff_profiles\``);
        await queryRunner.query(`DROP INDEX \`staff_profiles_business_id_fk\` ON \`staff_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_9162bf9ab4e31961a8f7932974\` ON \`transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_6711686e2dc4fcf9c7c83b8373\` ON \`user_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_9e144a67be49e5bba91195ef5d\` ON \`user_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_c1cf06e248522005c350032ee3\` ON \`wallets\``);
        await queryRunner.query(`DROP INDEX \`IDX_92558c08091598f7a4439586cd\` ON \`wallets\``);
        await queryRunner.query(`ALTER TABLE \`airtime_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`beneficiaries\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bill_mates_favourites\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`blue_admins\` CHANGE \`updated_at\` \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_branches\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_devices\` CHANGE \`created_at\` \`created_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_shareholders\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_settlement_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`kycs\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`otps\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payment_links\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`pins\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`recovery_infos\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`report_preferences\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`security_questions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_card_details\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_tokens\` CHANGE \`created_at\` \`created_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`ussd_withdrawals\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wallet_snapshots\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wallet_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wallets\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX \`id\` ON \`__drizzle_migrations\``);
        await queryRunner.query(`DROP TABLE \`__drizzle_migrations\``);
        await queryRunner.query(`DROP TABLE \`usersTest\``);
        await queryRunner.query(`ALTER TABLE \`airtime_transactions\` ADD CONSTRAINT \`airtime_transactions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_mates_favourites\` ADD CONSTRAINT \`bill_mates_favourites_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` ADD CONSTRAINT \`fk_airtime_staff_id\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` ADD CONSTRAINT \`fk_airtime_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_airtime_transactions\` ADD CONSTRAINT \`fk_airtime_branch_id\` FOREIGN KEY (\`branch_id\`) REFERENCES \`business_branches\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_branches\` ADD CONSTRAINT \`business_branches_ibfk_1\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` ADD CONSTRAINT \`fk_data_staff_id\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` ADD CONSTRAINT \`fk_data_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_data_transactions\` ADD CONSTRAINT \`fk_data_branch_id\` FOREIGN KEY (\`branch_id\`) REFERENCES \`business_branches\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` ADD CONSTRAINT \`fk_payment_staff_id\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` ADD CONSTRAINT \`fk_payment_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_payment_transactions\` ADD CONSTRAINT \`fk_payment_branch_id\` FOREIGN KEY (\`branch_id\`) REFERENCES \`business_branches\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_pins\` ADD CONSTRAINT \`business_pins_ibfk_1\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` ADD CONSTRAINT \`fk_power_staff_id\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` ADD CONSTRAINT \`fk_power_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_power_transactions\` ADD CONSTRAINT \`fk_power_branch_id\` FOREIGN KEY (\`branch_id\`) REFERENCES \`business_branches\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_profiles\` ADD CONSTRAINT \`fk_b_user_id\` FOREIGN KEY (\`b_user_id\`) REFERENCES \`business_users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_recovery_infos\` ADD CONSTRAINT \`business_recovery_infos_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`business_users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_shareholders\` ADD CONSTRAINT \`business_shareholders_ibfk_1\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_settlement_accounts\` ADD CONSTRAINT \`fk_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` ADD CONSTRAINT \`fk_tv_staff_id\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` ADD CONSTRAINT \`fk_tv_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_tv_transactions\` ADD CONSTRAINT \`fk_tv_branch_id\` FOREIGN KEY (\`branch_id\`) REFERENCES \`business_branches\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` ADD CONSTRAINT \`business_wallet_accounts_ibfk_2\` FOREIGN KEY (\`wallet_id\`) REFERENCES \`business_wallets\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_accounts\` ADD CONSTRAINT \`business_wallet_accounts_ibfk_1\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_wallet_snapshots\` ADD CONSTRAINT \`fk_walletsnapshot_history_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_wallets\` ADD CONSTRAINT \`business_wallets_ibfk_1\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dashme_transactions\` ADD CONSTRAINT \`dashme_transactions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`data_transactions\` ADD CONSTRAINT \`data_transactions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deleted_accounts\` ADD CONSTRAINT \`deleted_accounts_ibfk_1\` FOREIGN KEY (\`reason_id\`) REFERENCES \`reasons\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kycs\` ADD CONSTRAINT \`kycs_ibfk_2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kycs\` ADD CONSTRAINT \`kycs_ibfk_1\` FOREIGN KEY (\`document_type_id\`) REFERENCES \`document_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`notifications_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otps\` ADD CONSTRAINT \`otps_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pins\` ADD CONSTRAINT \`pins_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`power_transactions\` ADD CONSTRAINT \`power_transactions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recovery_infos\` ADD CONSTRAINT \`recovery_infos_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`report_preferences\` ADD CONSTRAINT \`FK_report_preferences_business_id\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`security_questions\` ADD CONSTRAINT \`security_questions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_profiles\` ADD CONSTRAINT \`staff_profiles_business_id_fk\` FOREIGN KEY (\`business_id\`) REFERENCES \`business_profiles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_profiles\` ADD CONSTRAINT \`staff_profiles_branch_fk\` FOREIGN KEY (\`branch_id\`) REFERENCES \`business_branches\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`transactions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tv_transactions\` ADD CONSTRAINT \`tv_transactions_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_accounts\` ADD CONSTRAINT \`user_accounts_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_card_details\` ADD CONSTRAINT \`user_card_details_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tokens\` ADD CONSTRAINT \`user_tokens_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallet_accounts\` ADD CONSTRAINT \`wallet_accounts_ibfk_2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallet_accounts\` ADD CONSTRAINT \`wallet_accounts_ibfk_1\` FOREIGN KEY (\`wallet_id\`) REFERENCES \`wallets\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallets\` ADD CONSTRAINT \`wallets_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
